adds GitHub Actions and build containers
hyperledger/indy-node pull request #1645
Opened 2021-02-05 21:38 UTC by m00sey

Signed-off-by: Kevin Griffin <griffin.kev@gmail.com>

2021-02-05 22:30 UTC, WadeBarnes commented
(ci) test this please

2021-02-06 16:35 UTC, WadeBarnes commented
(ci) test this please

2021-02-06 16:38 UTC, WadeBarnes approved these changes

2021-02-06 16:42 UTC, WadeBarnes requested changes

2021-02-06 16:42 UTC, WadeBarnes commented on ci/ubuntu.dockerfile
> +    libindy=1.15.0 \
Looks like this is causing a Jenkins build failure.
```
Version '1.15.0' for 'libindy' was not found
```

2021-02-07 16:18 UTC, WadeBarnes commented
(ci) test this please

2021-02-07 17:46 UTC, WadeBarnes approved these changes

2021-02-08 15:20 UTC, Toktar approved these changes

2021-02-08 16:06 UTC, merged