Add script for remove ledger
hyperledger/indy-node pull request #1650
Opened 2021-02-10 23:12 UTC by adenishchenko

Signed-off-by: anton.denishchenko <anton.denishchenko@evernym.com>

2021-02-11 08:13 UTC, askolesov requested changes
Looks good!

2021-02-11 08:13 UTC, askolesov commented on scripts/remove_ledger.py
> +def main(file_path):
Let's rename `file_parth` to `ledger_name`. What do you think? It's not a path actually.

2021-02-11 08:13 UTC, askolesov commented on scripts/remove_ledger.py
> +        print('Can`t delete ledger: ' + file_path)
```suggestion
        print('Can`t delete built in ledger: ' + file_path)
```

2021-02-11 08:13 UTC, askolesov commented on scripts/remove_ledger.py
> +            print('follow directory was deleted: ' + path.name)
```suggestion
            print('The follow directory was deleted: ' + path.name)
```

2021-02-11 09:15 UTC, askolesov commented
(ci) test this please

2021-02-11 12:55 UTC, WadeBarnes commented on scripts/remove_ledger.py
> +    exceptions = ["domen", "config", "pool", "audit"]
Should `domen` be `domain`?

2021-02-11 13:01 UTC, WadeBarnes requested changes
I'd highly recommend the script provide some feedback to the user and wait for confirmation. 
 It should clearly indicate it's about to delete a ledger, which ledger it's about to delete, describe the consequences, and then wait for confirmation from the user.

Some help text for the script would also be useful for those that are curious about what the script does, but don't want to read and fully understand the code.

2021-02-11 13:22 UTC, askolesov commented
@WadeBarnes Great ideas

2021-02-12 16:07 UTC, WadeBarnes requested changes
Looking good.  A few minor suggestions.

2021-02-12 16:07 UTC, WadeBarnes commented on scripts/remove_ledger.py
> +    print('The follow directories will be delete:')
```suggestion
    print('The follow directories will be deleted:')
```

2021-02-12 16:07 UTC, WadeBarnes commented on scripts/remove_ledger.py
> +    print('Delete ledger is irrevocable operation.\nProceed only if you know consequences.')
```suggestion
    print('Deleting a ledger is an irrevocable operation.\nProceed only if you know the consequences.')
```

2021-02-12 17:21 UTC, askolesov commented on scripts/remove_ledger.py
> +    print('The follow directories will be deleted:')
```suggestion
    print('The following directories will be deleted:')
```

2021-02-12 18:13 UTC, WadeBarnes requested changes
DCO sign-off is missing from your last commit.

2021-02-12 19:03 UTC, WadeBarnes commented
(ic) test this please.

2021-02-12 19:35 UTC, WadeBarnes requested changes
Code is failing static analysis; https://build.sovrin.org/job/indy-node/job/indy-node-verify-x86_64/2836/execution/node/18/log/

2021-02-15 07:46 UTC, askolesov approved these changes

2021-02-15 07:47 UTC, askolesov commented
(ci) test this please

2021-02-15 10:00 UTC, askolesov commented
(ci) ok to test

2021-02-15 11:39 UTC, askolesov commented
@WadeBarnes It seems that all comments were processed. Could you review this again, please?

2021-02-15 15:10 UTC, WadeBarnes approved these changes

2021-02-15 15:12 UTC, WadeBarnes commented
@Toktar, @skhoroshavin, We just need approval from a code owner.

2021-02-16 12:16 UTC, Toktar approved these changes

2021-02-16 12:17 UTC, merged