Fixes wrong max slices in GHA
hyperledger/indy-node pull request #1716
Opened 2021-11-26 10:33 UTC by pSchlarb

Signed-off-by: pSchlarb <p.schlarb@esatus.com>

2021-11-26 10:38 UTC, udosson commented
@pSchlarb thanks for the PR. Could you please provide some context and justify the proposed changes?

2021-11-26 11:08 UTC, pSchlarb commented
Yes, shimizut in the Rocketchat mentioned that the tests run by the GHA are only executing 11 of 22 slices per module. 
It seems that the variable used `strategy.job-total` is the sum of all slices across all modules.
So to correctly test all slices with the runner these changes are neccessary.

2021-11-26 16:36 UTC, WadeBarnes commented
I don't really like the idea of hard coding the number slices.  The original intent was to be able to update this section and have the test runs automatically adjust accordingly.  Obviously `strategy.job-total` is the number of modules * the number of slices.  We want it to just be the number of slices.  The question is how do we get that value without hard coding it.

```
      matrix:
        module: [indy_node, indy_common]
        slice: [1, 2, 3, 4 ,5, 6, 7, 8, 9, 10, 11]
```

2021-11-26 16:55 UTC, WadeBarnes commented
It does not seem to be a way to get the count of items included in the elements of a matrix.

What if we added a `slice_count` environment variable and had it set to the total number of slices, and documented it has to match the number of elements contained in `strategy.matrix.slice`.  It's still a bit of a hack, but better then having to change the value in multiple places is/when the number of elements contained in `strategy.matrix.slice` is changed.

2021-11-29 15:00 UTC, pSchlarb commented
I am fine with that but i would call it `SLICE_TOTAL_SLICES`.

2021-11-29 15:22 UTC, WadeBarnes requested changes

2021-11-29 15:22 UTC, WadeBarnes commented on .github/workflows/build.yaml
> +      SLICE_TOTAL_SLICES: 11
Please add a note to indicate the value needs to match the total number if items listed in the `strategy.matrix.slice` element.

2021-11-29 15:46 UTC, WadeBarnes commented
(ci) test this please

2021-11-29 15:46 UTC, WadeBarnes approved these changes

2021-11-29 16:53 UTC, merged