New Release Workflow & Gha refactoring
hyperledger/indy-node pull request #1749
Opened 2022-05-10 14:29 UTC by pSchlarb

Refactoring of GHA Workflows and New Release Workflow.
PR and Push flows now only trigger, when python files have changed.

WIP: 
+ Workflow for automated node upgrades after plenum updates
+ indy-test-automation integration

New Release Workflow:
![release-workflow](https://user-images.githubusercontent.com/87540518/167651914-06c07b62-b685-4cca-adf3-f007b34346e3.png)

2022-05-12 17:05 UTC, WadeBarnes requested changes
A few small items to address.

The `publish-deb` and `set-version`  actions should be removed now that they are in the `indy-shared-gha` repo.

The ubuntu 16.04 build scripts were removed from this PR, should they have also been removed from the indy-plenum PR; https://github.com/hyperledger/indy-plenum/pull/1590

Renaming of `build-scripts/ubuntu-2004/build-indy-node.sh` to `build-scripts/ubuntu-2004/build-indy_node.sh`.  This is inconsistent with the renaming of the equivalent script in plenum from `build-scripts/ubuntu-2004/build-indy-plenum.sh` to `build-scripts/ubuntu-2004/build-plenum.sh`

Also see https://github.com/hyperledger/indy-plenum/issues/1592

2022-05-13 08:17 UTC, pSchlarb commented
> Renaming of `build-scripts/ubuntu-2004/build-indy-node.sh` to `build-scripts/ubuntu-2004/build-indy_node.sh`. This is inconsistent with the renaming of the equivalent script in plenum from `build-scripts/ubuntu-2004/build-indy-plenum.sh` to `build-scripts/ubuntu-2004/build-plenum.sh`

That was intentionally done to match the `moduleName`-variable.
As can be seen in the [`buildpackage.yaml`](https://github.com/hyperledger/indy-shared-gha/blob/cc5e2379ef9ecd7738a6ca65ee92e222f702aaad/.github/workflows/buildpackages.yaml#L47)

2022-05-13 08:27 UTC, pSchlarb commented on .github/workflows/tag.yaml
> +        run: pip install base58
I will add it but wouldn't it be wiser to change the `bump_version.sh` script to only change the `__version__.json`?

2022-05-13 15:59 UTC, WadeBarnes requested changes
Need to separate the `apt-get` and `pip` commands

2022-05-13 15:59 UTC, WadeBarnes commented on .github/workflows/tag.yaml
> +                       libgflags-dev \
```suggestion
                       libgflags-dev
```

2022-05-13 16:52 UTC, WadeBarnes requested changes
This one was my oversite in the first review.

2022-05-13 16:52 UTC, WadeBarnes commented on .github/workflows/releasepr.yaml
> +    needs: [release-infos, build-image]
```suggestion
    needs: [release-infos, build-docker-image]
```

2022-05-16 12:29 UTC, WadeBarnes approved these changes

2022-05-16 12:29 UTC, merged